Create Packer file system
gohypergiant/firefly pull request #8
Opened 2021-10-14 22:44 UTC by Shazzberry

2021-10-15 01:45 UTC, bbriggs requested changes
If you change the name of the packer build file, you also need to update the GH action which is currently looking for `firefly.pkr.hcl`

2021-10-15 01:45 UTC, bbriggs commented on packer/sources.pkr.hcl
> +    }
We aren't (yet) assuming a role

2021-10-15 20:43 UTC, Shazzberry commented
ready for another review i think

2021-10-19 14:01 UTC, bbriggs commented
There is an existing conflict. Is this PR still valid?

2021-10-21 18:01 UTC, closed without merging